use std::{env, fs, path::PathBuf};

#[derive(Debug, Clone, Copy)]
struct ParsedVersion {
    minor: u64,
}

fn parse_v0_semver(version: &str) -> Option<ParsedVersion> {
    let mut parts = version.split('.');
    let major = parse_semver_part(parts.next()?)?;
    let minor = parse_semver_part(parts.next()?)?;
    parse_semver_part(parts.next()?)?;
    if parts.next().is_some() || major != 0 {
        return None;
    }
    Some(ParsedVersion { minor })
}

fn parse_semver_part(part: &str) -> Option<u64> {
    if part.is_empty() || !part.bytes().all(|byte| byte.is_ascii_digit()) {
        return None;
    }
    if part.len() > 1 && part.starts_with('0') {
        return None;
    }
    part.parse().ok()
}

fn main() {
    let package_version =
        env::var("CARGO_PKG_VERSION").expect("Cargo must provide CARGO_PKG_VERSION");
    let parsed = parse_v0_semver(&package_version)
        .expect("skenion-contracts package version must be v0 SemVer major.minor.patch");
    let compatibility_line = format!("0.{}", parsed.minor);
    let compatibility_range = format!(">=0.{}.0 <0.{}.0", parsed.minor, parsed.minor + 1);

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("Cargo must provide OUT_DIR"));
    fs::write(
        out_dir.join("version_constants.rs"),
        format!(
            concat!(
                "// This file is generated by packages/rust/build.rs from Cargo package metadata.\n",
                "pub const CONTRACTS_COMPATIBILITY_LINE: &str = {compatibility_line:?};\n",
                "pub const CONTRACTS_COMPATIBILITY_RANGE: &str = {compatibility_range:?};\n"
            ),
            compatibility_line = compatibility_line,
            compatibility_range = compatibility_range
        ),
    )
    .expect("version constants should be writable");

    println!("cargo:rerun-if-changed=Cargo.toml");
}
